spring:
  datasource:
#    配置数据库相关信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydata
    username: root
    password: root

mybatis:
  configuration:
#    开启控制太输出sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    开启驼峰命名自动映射
    map-underscore-to-camel-case: true
  type-aliases-package: com.cqupt.entity
